# Generated by Django 4.0.1 on 2022-01-25 06:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
