# Generated by Django 4.0.1 on 2022-01-26 11:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_blogs_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('desc', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
