# Generated by Django 4.0.1 on 2022-01-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_blogs_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='url',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
