# Generated by Django 4.0.1 on 2022-01-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_blogs_url_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
